#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_win_scheduled_task(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(cmk.utils.paths.local_agents_dir + "/windows/plugins/win_scheduled_task.ps1",
                 plugins_dir + "/win_scheduled_task.ps1")

bakery_info["win_scheduled_task"] = {
    "bake_function" : bake_win_scheduled_task,
    "os"            : [ "windows" ],
}
